lsi: false
safe: true
source: https://github.com/Kalebeadv/gerenciamento-escolar.github.io
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

theme: jekyll-theme-cayman
